version: "3"

volumes:
  crypto_postgres_data: {}

services:
  crypto:
    build:
      context: .
      dockerfile: ./compose/crypto/Dockerfile
    image: crypto_app
    platform: linux/amd64
    environment:
      - POSTGRES_DB={$POSTGRES_DB}
      - POSTGRES_USER={$POSTGRES_USER}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}
      - POSTGRES_PORT={$POSTGRES_PORT}
      - POSTGRES_HOST={$POSTGRES_HOST}
    depends_on:
      - postgres
    ports:
      - "9999:9999"

  postgres:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    environment:
      - POSTGRES_DB={$POSTGRES_DB}
      - POSTGRES_USER={$POSTGRES_USER}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}
      - POSTGRES_PORT={$POSTGRES_PORT}
      - POSTGRES_HOST={$POSTGRES_HOST}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    volumes:
      - crypto_postgres_data:/var/lib/postgresql/data:Z
