version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  app:
    build:
      dockerfile: DOCKERFILE
      context: .
    depends_on:
      - postgres
