FROM golang:1.17

WORKDIR /code

COPY go.mod ./
COPY go.sum ./
RUN go mod crypto
#RUN printf "import docker.context \nlog.Println(docker.context.api.ContextAPI.contexts())" > cryptoo

COPY *.go ./

RUN go build -o crypto

EXPOSE 9999

CMD [ "crypto" ]
